### ISSUE TITLE
Gui update from v2.2.3 failed

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/wallabag2_ynh#40]
I'm in v2.2.3, and try to update from the administration frontend page. It seems to fail doing the backup:

> [...]
>     2017-07-26 20:16:42,044 INFO     yunohost.hook &lt;lambda&gt; - [535.7] + ynh_backup_before_upgrade
>     2017-07-26 20:16:42,050 INFO     yunohost.hook &lt;lambda&gt; - [535.7] + backup_number=1
>     2017-07-26 20:16:42,051 INFO     yunohost.hook &lt;lambda&gt; - [535.7] + old_backup_number=2
>     2017-07-26 20:16:42,054 INFO     yunohost.hook &lt;lambda&gt; - [535.7] + app_bck=wallabag2
>     2017-07-26 20:16:42,058 INFO     yunohost.hook &lt;lambda&gt; - [535.7] + grep -q wallabag2-pre-upgrade1
>     2017-07-26 20:16:42,059 INFO     yunohost.hook &lt;lambda&gt; - [535.7] + sudo yunohost backup list
>     2017-07-26 20:16:45,934 INFO     yunohost.hook &lt;lambda&gt; - [535.7] + sudo yunohost backup create --ignore-hooks --apps wallabag2 --name wallabag2-pre-upgrade1
>     2017-07-26 20:16:49,724 WARNING  yunohost.hook &lt;lambda&gt; - [535.7] --ignore-hooks is deprecated and will be removed in thefuture. Please use --ignore-system instead.
>     2017-07-26 20:16:49,728 WARNING  yunohost.hook &lt;lambda&gt; - [535.7] Le dossier de sortie n'est pas vide
>     2017-07-26 20:16:49,887 ERROR    yunohost.app app_upgrade - [535.7] Impossible de mettre à jour wallabag2
>     2017-07-26 20:16:49,889 WARNING  yunohost.tools tools_upgrade - [535.7] unable to upgrade apps: [Errno 61] Aucune application à mettre à jour
>     2017-07-26 20:16:49,890 INFO     moulinette.core translate - untranslated key 'app_upgrade_failed' for locale 'fr'
>     2017-07-26 20:16:49,890 ERROR    moulinette.core translate - unable to retrieve key 'app_upgrade_failed' for default locale 'en'
>     Traceback (most recent call last):
>       File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 201, in translate
>         return _load_key(self.default_locale)
>       File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 192, in _load_key
>         return value.encode('utf-8').format(*args, **kwargs)
>     KeyError: 'app'
>     2017-07-26 20:16:49,891 ERROR    yunohost.tools tools_upgrade - [535.7] app_upgrade_failed

No Wallabag backup found in /home/yunohost.backup/

**Comment by klorydryk** [comment]
How to bypass this error: look in /home/yunohost.backup/tmp and remove the wallabag backup remaining inside.
Restart the backup.
